#ifndef SDKCONFIG_H
#define SDKCONFIG_H

/*
 * Minimal stub for Arduino/PlatformIO builds.
 *
 * In ESP-IDF projects this file is generated by menuconfig and contains
 * many CONFIG_* macros. For this Arduino build we keep it intentionally
 * minimal so third-party headers that unconditionally include
 * "sdkconfig.h" can still compile.
 */

#endif // SDKCONFIG_H
