#ifndef SDKCONFIG_H
#define SDKCONFIG_H

/*
 * Minimal stub for Arduino/PlatformIO builds.
 * The ESP-IDF version of this header is normally generated by the
 * build system (menuconfig) and contains hundreds of CONFIG_ macros.
 * Here we keep it empty (or add only the symbols that are required by
 * third‑party libraries) so that headers which unconditionally
 * include "sdkconfig.h" can compile without providing the whole
 * IDF configuration.
 */

/* Example of how to enable a feature if you actually need it:
   #define CONFIG_LITTLEFS_PAGE_SIZE 256
   #define CONFIG_LV_USE_FS_LITTLEFS 1
*/

#endif // SDKCONFIG_H
